<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div class="container">

            {% block content %}{% endblock %}
            
        </div>
    </body>
</html>